src/Entity/Personne.php
<?php

namespace App\Entity;

use App\Repository\PersonneRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PersonneRepository::class)
 * @ORM\Table(name="personnes")
 */
class Personne
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }
}

src/Form/PersonneType.php
<?php

namespace App\Form;

use App\Entity\Personne;
use App\Validator\ConstraintsDate;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_naissance', DateType::class, [
                'widget'=>'single_text',
                'required'=>true,
                'constraints'=>([
                    new ConstraintsDate([
                        'year' => 150,
                    ]),
                ])
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Personne::class,
        ]);
    }
}

src/Controller/PersonneController.php
<?php

namespace App\Controller;

use App\Entity\Personne;
use App\Form\PersonneType;
use App\Repository\PersonneRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PersonneController extends AbstractController
{
    /**
     * @Route("/", name="app_personne", methods={"GET", "POST"})
     */
    public function index(Request $request, EntityManagerInterface $em): Response
    {
        $personne = new Personne();
        $personne->setDateNaissance(new \DateTimeImmutable);
        $form = $this->createForm(PersonneType::class, $personne);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($personne);
            $em->flush();
            $this->addFlash('success', "L'enregistrement s'est bien effectué");
        }

        return $this->render('personne/index.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/show", name="app_personne_show",methods={"GET"})
     */
    public function show(PersonneRepository $personneRepository): Response
    {
        $personnes = $personneRepository->findBy([], ['nom' => 'DESC']);
        return $this->render('personne/show.html.twig', compact("personnes"));
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
    {% block stylesheets %}
        {# {{ encore_entry_link_tags('app') }} #}
    {% endblock %}

    {% block javascripts %}
        {# {{ encore_entry_script_tags('app') }} #}
    {% endblock %}
</head>
<body>
{% for type, messages in app.flashes(['success', 'error', 'info']) %}
    {% for message in messages %}
        <div class="alert alert-{{ type }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endfor %}

{% block body %}{% endblock %}
</body>
</html>

templates/personne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personne{% endblock %}

{% block body %}
    <h1>Formulaire enregistrement</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}

    <input type="submit" value="Valider" class="btn btn-primary btn-block" formnovalidate>
    {{ form_end(form) }}


    <a href="{{path("app_personne_show")}}">
    Liste des personnes
    </a>


{% endblock %}

templates/personne/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personne{% endblock %}

{% block body %}
    <h1>Liste des enregistrements</h1>

    <table>
        <tr>
            <td>Nom</td>
            <td>Prénom</td>
            <td>Date de naissance</td>
        </tr>
        {% for personne in personnes %}
            <tr>
                <td>{{ personne.nom }}</td>
                <td>{{ personne.prenom }}</td>
                <td>{{ personne.dateNaissance|date("d/m/y") }}</td>

            </tr>
        {% endfor %}
    </table>

    <a href="{{path("app_personne")}}">
        Back
    </a>


{% endblock %}